import Head from 'next/head'
import { ContractView } from '../views'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Work Not Boring</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContractView />
    </div>
  );
}
